require "rubygems"
require "bundler/setup"
require "oauth2"
require "json"

require "cloudprint/version"
require "cloudprint/client"
require "cloudprint/auth"
require "cloudprint/printer_collection"
require "cloudprint/printer"
require "cloudprint/connection"
require "cloudprint/print_job_collection"
require "cloudprint/print_job"
require "cloudprint/exceptions"
